config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions', passwords: 'admins/passwords'
  }

  # JS Testing
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  # Dashboard
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'welcome/index'

  root 'welcome#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable,
         :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/admins/confirmations_controller.rb
class Admins::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admins/omniauth_callbacks_controller.rb
class Admins::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admins/passwords_controller.rb
class Admins::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admins/registrations_controller.rb
class Admins::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admins/unlocks_controller.rb
class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def site_name
    ENV['SITE_NAME']
  end

  def icon(name)
    render "/application/icons/#{name}"
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_nav.html.slim
nav
  .nav-wrapper
    .row
      .col.s12
        a.brand-logo.center href=root_path title=site_name
          i.white-text= icon 'logo'
        - if current_admin
          ul#nav-mobile.right
            li
              a  href='#'
                span.glyphicon.glyphicon-log-in
                  'Dashboard
            li
              a
                i.material-icons more_vert

app/views/application/icons/_logo.html.slim
svg height="100%" preserveAspectRatio=("xMidYMid meet") version="1.0" viewBox=("0 0 368.000000 162.000000") width="100%" xmlns="//www.w3.org/2000/svg"
  g fill="#000000" stroke="none" transform="translate(0.000000,162.000000) scale(0.100000,-0.100000)"
    path d=("M295 1498 c-2 -7 -18 -78 -34 -158 -59 -285 -132 -629 -180 -845 -26\n-121 -47 -221 -46 -223 4 -4 168 -43 170 -40 4 6 108 475 140 628 l31 155 205\n3 206 2 15 75 14 75 -203 0 c-112 0 -203 3 -203 8 1 4 9 45 18 92 l18 85 872\n3 872 2 0 75 0 75 -945 0 c-748 0 -947 -3 -950 -12z")
  g fill="#000000" stroke="none" transform="translate(0.000000,162.000000) scale(0.100000,-0.100000)"
    path d=("M570 1285 l0 -45 185 0 c213 0 194 14 170 -120 -15 -84 -53 -320\n-115 -715 l-32 -200 -202 0 -201 0 -3 -47 -3 -48 521 0 521 0 -3 48 -3 47\n-222 0 -223 0 5 30 c3 17 19 116 36 220 16 105 50 313 74 463 25 150 45 284\n45 298 l0 24 245 0 245 0 0 45 0 45 -520 0 -520 0 0 -45z")
  g fill="#000000" stroke="none" transform="translate(0.000000,162.000000) scale(0.100000,-0.100000)"
    path d=("M2017 1268 c-6 -23 -81 -382 -138 -658 -17 -80 -32 -151 -34 -157 -3\n-10 19 -13 89 -13 l93 0 12 62 c38 198 35 191 118 263 62 54 78 64 88 53 7 -7\n54 -95 106 -196 l94 -182 180 0 181 0 85 152 c48 84 128 231 179 326 51 95 94\n171 96 170 1 -2 12 -70 23 -153 12 -82 28 -188 36 -235 8 -47 19 -124 26 -172\nl12 -88 90 0 c87 0 89 0 84 22 -8 30 -37 209 -37 226 0 9 30 12 115 12 l115 0\n0 65 0 65 -128 0 -127 0 -33 213 c-19 116 -36 220 -39 230 -4 16 -16 17 -105\n15 l-101 -3 -114 -200 c-62 -110 -166 -293 -230 -407 -64 -115 -117 -207 -119\n-205 -5 5 -253 463 -256 473 -3 9 93 97 309 284 l63 55 -122 3 -122 3 -70 -69\nc-93 -90 -306 -285 -306 -281 0 2 16 78 35 168 19 90 35 167 35 172 0 5 -40 9\n-89 9 -84 0 -89 -1 -94 -22z")
  g fill="#000000" stroke="none" transform="translate(0.000000,162.000000) scale(0.100000,-0.100000)"
    path d=("M1271 1169 c-10 -23 -161 -681 -161 -700 0 -13 370 -11 432 2 149 31\n263 143 303 299 43 168 -11 319 -137 383 -54 28 -62 29 -241 34 l-186 6 -10\n-24z m358 -137 c43 -31 56 -69 55 -157 0 -87 -19 -144 -70 -210 -44 -58 -93\n-78 -210 -83 l-101 -5 33 149 c19 82 44 191 56 243 l21 94 95 -6 c72 -4 102\n-10 121 -25z")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1' }
    %title= site_name
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'nav'
    .container= yield

app/views/layouts/application.html.slim
doctype html
html
  head
    meta  content='text/html; charset=UTF-8' http-equiv='Content-Type'
    meta  name='viewport' content='width=device-width, initial-scale=1'
    title= site_name
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'nav'
    .container= yield

app/views/welcome/index.html.slim
h1 Welcome#index
p Find me in app/views/welcome/index.html.erb